export { default as CHeader } from './C-Header.vue'
export {default as CSendEmail} from './C-Mailer.vue'
export { default as CDialog } from './C-Dialog.vue'
export {default as CProfile } from './C-Profile.vue'
export {default as CMenu } from './C-Menu.vue'
export {default as CChart } from './C-Chart.vue'
export {default as CChartConnection } from './C-ChartConnection.vue'
export {default as CNotifications } from './C-Notifications.vue'
export {default as CVideogamesUploaded } from './C-VideogamesUploaded.vue'
export {default as CVideogamesReported } from './C-VideogamesReported.vue'