export { default as CHeader } from './C-Header.vue'
export {default as CSendEmail} from './C-Mailer.vue'
export {default as CSearchBar } from './C-Search.vue'
export {default as CProfile } from './C-Profile.vue'
export {default as CDialog} from './C-Dialog.vue'